services:
  # 1. Online Backend REST API Service
  - type: web
    name: mini-erp-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install && npx prisma generate && npm run build
    startCommand: cd server && npx prisma db push && npx ts-node prisma/seed.ts && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        value: "postgresql://postgres.ijnnazbvnufevfyappts:P5Vqn0ALIGxUcJsG@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres"
      - key: JWT_SECRET
        generateValue: true

  # 2. Online React Frontend Web App
  - type: web
    name: mini-erp-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# 3. Online Managed PostgreSQL Database
databases:
  - name: mini-erp-db
    plan: free
    databaseName: minierpdb
    user: minierpuser
